FROM python:2.7

MAINTAINER Johann Fuechsl <fuechsl@redlever.solutions>

RUN apt-get update && \
    apt-get install -y redis-server supervisor && \
    ln -s /src/tipboard-config /root/.tipboard && \
    mkdir /root/logs

COPY requirements-tipboard.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY tipboard-image/supervisord.conf /etc/supervisor/supervisord.conf

EXPOSE 8080

CMD ["/usr/bin/supervisord", "-j", "/root/supervisord.pid"]
