FROM python:2.7

MAINTAINER Johann Fuechsl <fuechsl@redlever.solutions>

RUN apt-get update && \
    apt-get install -y --force-yes redis-server supervisor && \
    ln -s /src/tipboard-config /root/.tipboard && \
    mkdir /root/logs && \
    mkdir /src && \
    git clone git://github.com/red-lever-solutions/tipboard /src/tipboard && \
    cd /src/tipboard && pip install .

COPY tipboard-image/supervisord.conf /etc/supervisor/supervisord.conf

COPY src/tipboard-config /src/tipboard-config

EXPOSE 8080

CMD ["/usr/bin/supervisord", "-j", "/root/supervisord.pid"]
