version: "2"

services:
  checker:
    build:
      context: .
      dockerfile: Dockerfile-checker
    volumes:
      - ./src:/src
      - ./config:/config
      - ./status:/status
      - ./logs:/logs
    environment:
      PYTHONUNBUFFERED: "1"

  tipboard:
    build:
      context: .
      dockerfile: Dockerfile-tipboard
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
