FROM python:3.5

MAINTAINER Johann Fuechsl <fuechsl@redlever.solutions>

VOLUME /config
VOLUME /status
VOLUME /logs

RUN apt-get update && apt-get install -y --force-yes openssh-client

COPY requirements-checker.txt /requirements.txt
RUN pip install -r requirements.txt

COPY src/checker /src/checker

WORKDIR /src
CMD ["python", "-m", "checker.runner"]
